# Generated by Django 3.0.5 on 2020-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Birding location')),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='invasive',
            field=models.BooleanField(default=False, verbose_name='Invasive?'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='habitat',
            field=models.CharField(choices=[('G', 'On the ground'), ('T', 'In trees or bushes'), ('P', 'Perched on a fence or wire'), ('N', 'In a nest'), ('F', 'Flying'), ('W', 'Wading or swimming'), ('E', 'Eating at a feeder')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='bird',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
