# Generated by Django 3.0.5 on 2020-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200618_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default='Location description', max_length=250),
            preserve_default=False,
        ),
    ]
