# Generated by Django 3.0.5 on 2020-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
