# Generated by Django 3.0.5 on 2020-06-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_sighting_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='BirdPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bird')),
            ],
        ),
    ]
